from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np

from indep_mu.dicom.ct import CtSeries

from .discretize import DiscreteMaterialField, EGSPHANT_MAX_MEDIA
from .model import PatientModel


EGSPHANT_ENCODING = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"


@dataclass(frozen=True)
class EgsphantGeometry:
    """Local right-handed CT basis and voxel boundaries for DOSXYZnrc."""

    x_bound_cm: np.ndarray
    y_bound_cm: np.ndarray
    z_bound_cm: np.ndarray
    x_direction_patient: tuple[float, float, float]
    y_direction_patient: tuple[float, float, float]
    z_direction_patient: tuple[float, float, float]

    @property
    def shape_zyx(self) -> tuple[int, int, int]:
        return (
            int(self.z_bound_cm.size - 1),
            int(self.y_bound_cm.size - 1),
            int(self.x_bound_cm.size - 1),
        )


@dataclass(frozen=True)
class EgsphantData:
    media_names: tuple[str, ...]
    geometry: EgsphantGeometry
    medium_index: np.ndarray
    mass_density_g_cm3: np.ndarray


def build_egsphant_geometry(ct: CtSeries, model: PatientModel) -> EgsphantGeometry:
    """Map the cropped CT grid into a local DOSXYZnrc x/y/z coordinate system.

    x follows increasing DICOM column index (first ImageOrientationPatient
    vector), y follows increasing row index (second vector), and z is their
    right-handed cross product. Coordinates remain tied to the DICOM patient
    frame through these direction cosines.
    """

    orientation = np.asarray(
        ct.geometry.image_orientation_patient, dtype=np.float64
    )
    x_direction = orientation[:3]
    y_direction = orientation[3:]
    z_direction = np.cross(x_direction, y_direction)
    z_direction /= np.linalg.norm(z_direction)

    row_spacing_mm, column_spacing_mm = ct.geometry.pixel_spacing_mm
    bounds = model.crop_bounds

    first_slice_position = ct.image_positions_patient_mm[bounds.z_start]

    x_first_center_mm = (
        float(np.dot(first_slice_position, x_direction))
        + bounds.x_start * column_spacing_mm
    )
    y_first_center_mm = (
        float(np.dot(first_slice_position, y_direction))
        + bounds.y_start * row_spacing_mm
    )
    z_first_center_mm = float(ct.slice_positions_mm[bounds.z_start])

    nz, ny, nx = model.shape

    x_bound_mm = (
        x_first_center_mm
        - 0.5 * column_spacing_mm
        + np.arange(nx + 1, dtype=np.float64) * column_spacing_mm
    )
    y_bound_mm = (
        y_first_center_mm
        - 0.5 * row_spacing_mm
        + np.arange(ny + 1, dtype=np.float64) * row_spacing_mm
    )
    z_bound_mm = (
        z_first_center_mm
        - 0.5 * ct.geometry.slice_spacing_mm
        + np.arange(nz + 1, dtype=np.float64) * ct.geometry.slice_spacing_mm
    )

    return EgsphantGeometry(
        x_bound_cm=x_bound_mm / 10.0,
        y_bound_cm=y_bound_mm / 10.0,
        z_bound_cm=z_bound_mm / 10.0,
        x_direction_patient=tuple(float(v) for v in x_direction),
        y_direction_patient=tuple(float(v) for v in y_direction),
        z_direction_patient=tuple(float(v) for v in z_direction),
    )


def _medium_character(index: int) -> str:
    if not 1 <= index <= EGSPHANT_MAX_MEDIA:
        raise ValueError(
            f"egsphant medium index must be in [1, {EGSPHANT_MAX_MEDIA}], got {index}."
        )
    # EGSnrc uses index(encoding, char)-1 on input, so medium 1 is encoding[1].
    return EGSPHANT_ENCODING[index]


def _medium_index(character: str) -> int:
    position = EGSPHANT_ENCODING.find(character)
    if position <= 0:
        raise ValueError(f"Invalid egsphant medium character: {character!r}")
    return position


def write_egsphant(
    path: str | Path,
    *,
    ct: CtSeries,
    model: PatientModel,
    discrete: DiscreteMaterialField,
) -> EgsphantGeometry:
    """Write a standard text .egsphant readable by DOSXYZnrc.

    Material names are generated by the discretizer and must be defined in the
    matching EGSnrc pegsless/PEGS material set before transport.
    """

    output = Path(path)
    geometry = build_egsphant_geometry(ct, model)

    if discrete.medium_index.shape != model.shape:
        raise ValueError(
            "Discrete medium-index field shape does not match PatientModel."
        )
    if len(discrete.media) > EGSPHANT_MAX_MEDIA:
        raise ValueError(
            f"egsphant supports at most {EGSPHANT_MAX_MEDIA} media."
        )
    if np.any(discrete.medium_index < 1) or np.any(
        discrete.medium_index > len(discrete.media)
    ):
        raise ValueError("Medium-index field contains an undefined medium.")

    names = tuple(item.egsphant_name for item in discrete.media)
    if any(len(name) > 24 for name in names):
        raise ValueError("egsphant medium names must be at most 24 characters.")
    if len(set(names)) != len(names):
        raise ValueError("egsphant medium names must be unique.")

    nz, ny, nx = model.shape
    density = np.asarray(model.mass_density_g_cm3, dtype=np.float64)

    with output.open("w", encoding="ascii", newline="\n") as stream:
        stream.write(f"{len(names):2d}\n")
        for name in names:
            stream.write(f"{name:<24}\n")

        stream.write(" ".join("1.0" for _ in names) + "\n")
        stream.write(f"{nx:5d}{ny:5d}{nz:5d}\n")

        for vector in (
            geometry.x_bound_cm,
            geometry.y_bound_cm,
            geometry.z_bound_cm,
        ):
            stream.write(" ".join(f"{value:.10g}" for value in vector) + "\n")

        for k in range(nz):
            for j in range(ny):
                row = "".join(
                    _medium_character(int(value))
                    for value in discrete.medium_index[k, j, :]
                )
                stream.write(row + "\n")
            stream.write("\n")

        for k in range(nz):
            for j in range(ny):
                stream.write(
                    " ".join(f"{value:.9g}" for value in density[k, j, :])
                    + "\n"
                )
            stream.write("\n")

    return geometry


def _read_numeric_values(
    lines: list[str],
    position: int,
    count: int,
    *,
    converter,
) -> tuple[np.ndarray, int]:
    values: list[float | int] = []
    while len(values) < count:
        if position >= len(lines):
            raise ValueError("Unexpected end of egsphant while reading numeric data.")
        line = lines[position].strip()
        position += 1
        if not line:
            continue
        values.extend(converter(token) for token in line.split())

    if len(values) != count:
        raise ValueError("Too many values on egsphant numeric line group.")

    return np.asarray(values), position


def read_egsphant(path: str | Path) -> EgsphantData:
    """Read the subset of the standard .egsphant format written by this project."""

    input_path = Path(path)
    lines = input_path.read_text(encoding="ascii").splitlines()
    position = 0

    if not lines:
        raise ValueError("Empty egsphant file.")

    nmed = int(lines[position].strip())
    position += 1
    if not 1 <= nmed <= EGSPHANT_MAX_MEDIA:
        raise ValueError(f"Invalid number of egsphant media: {nmed}.")

    names: list[str] = []
    for _ in range(nmed):
        if position >= len(lines):
            raise ValueError("Unexpected end of egsphant while reading media names.")
        names.append(lines[position].strip())
        position += 1

    # ESTEPE values are retained for format compatibility but controlled by
    # EGSnrc transport inputs, as in ctcreate.
    _, position = _read_numeric_values(
        lines, position, nmed, converter=float
    )

    dimensions, position = _read_numeric_values(
        lines, position, 3, converter=int
    )
    nx, ny, nz = (int(value) for value in dimensions)

    x_bound, position = _read_numeric_values(
        lines, position, nx + 1, converter=float
    )
    y_bound, position = _read_numeric_values(
        lines, position, ny + 1, converter=float
    )
    z_bound, position = _read_numeric_values(
        lines, position, nz + 1, converter=float
    )

    medium = np.empty((nz, ny, nx), dtype=np.uint8)
    for k in range(nz):
        for j in range(ny):
            while position < len(lines) and not lines[position]:
                position += 1
            if position >= len(lines):
                raise ValueError(
                    "Unexpected end of egsphant while reading medium map."
                )
            row = lines[position].rstrip("\n")
            position += 1
            if len(row) != nx:
                raise ValueError(
                    f"Medium row length {len(row)} does not match nx={nx}."
                )
            medium[k, j, :] = [
                _medium_index(character) for character in row
            ]

    density_values, position = _read_numeric_values(
        lines, position, nx * ny * nz, converter=float
    )
    density = density_values.astype(np.float32).reshape((nz, ny, nx))

    geometry = EgsphantGeometry(
        x_bound_cm=x_bound.astype(np.float64),
        y_bound_cm=y_bound.astype(np.float64),
        z_bound_cm=z_bound.astype(np.float64),
        # Orientation is not stored in the legacy egsphant itself.
        x_direction_patient=(1.0, 0.0, 0.0),
        y_direction_patient=(0.0, 1.0, 0.0),
        z_direction_patient=(0.0, 0.0, 1.0),
    )

    return EgsphantData(
        media_names=tuple(names),
        geometry=geometry,
        medium_index=medium,
        mass_density_g_cm3=density,
    )
